name: Site

on:
  push:
    branches:
      - site

jobs:
  build:
    if: github.repository_owner == 'spotbugs' && ! contains(toJSON(github.event.head_commit.message), '[maven-release-plugin]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Build site
        run: ./mvnw site site:stage -DskipTests -Dlicense.skip=true -B -V --no-transfer-progress
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Site to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: spotbugs/spotbugs-maven-plugin.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
